### ISSUE TITLE
Missing the interpreter as example?

### ISSUE THREAD

**Issue by jiamo** [dabeaz/wadze#1]
The video https://www.youtube.com/watch?v=r-A78RgMhZU show an amazing interpreter.
We can type exactly the same from the video.  If you offer it as example , we can do some changes for fun. (This will be save some time or may be lost our own fun. ) Can this happen?

**Comment by dabeaz** [comment]
Code for the video can be obtained at https://gist.github.com/dabeaz/7d8838b54dba5006c58a40fc28da9d5a

I'm not inclined to include this code in the wadze repository directly because it is more a piece of "performance art" than something that I want to turn into a serious project (it's also incomplete and doesn't implement every instruction).  Wadze, however, is a serious project that I'd like to use for building some other more practical WebAssembly related tools.
